### ISSUE TITLE
The dunstrc leads to another dunstrc we don't have access to.

### ISSUE THREAD

**Issue by sfulham** [CaptainEureka/dotfiles#1]
The dunstrc leads to another dunstrc we don't have access to. Can you either modify the one thats in the folder or give us the other one, 

Thanks.

**Comment by CaptainEureka** [comment]
Should be fixed with the most recent push. The dunstrc file is a pywal template, it's in wal/templates/dunstrc. **Note:** You will need to rerun pywal to generate the config.
